### ISSUE TITLE
Include ACE.md inside release package

### ISSUE THREAD

**Issue by Armaldio** [TobyReeno/c2-addon-assistant#1]
Is it possible to include ACE.md package inside the release archive ?
Maybe with an extra argument

**Comment by TobyReeno** [comment]
I'm not sure if end-user is interested in ACE.md? He already has the plugin so he sees the ACEs in Construct.

I think ACE.md is useful here on Git to show the plugin ACEs before one downloads it.

**Comment by Armaldio** [comment]
Well.. Yes ^^'
