### ISSUE TITLE
Local configuration file

### ISSUE THREAD

**Issue by Armaldio** [TobyReeno/c2-addon-assistant#5]
It could be usefull to have a configuration file local to the folder
This way we could define a custom name or ignore files for the release/update

```json
{
     "name": "my plugin",
     "ignore": [
            ".git/**",
             ".gitignore",
             "node_modules/**"
       ],
       "type": "plugin",
       "version": 0.1,
        "etc..."
}
```

**Comment by TobyReeno** [comment]
I wanted this tool to be a minimalistic tool for rapid dev-support. I don't see the reason to keep an extra file for a plugin name while we can use the directory name (helps with organizing also) or to keep the version name while we can use the plugin's XML.

Also no need to ignore anything cause it just copies/zips the needed files. 

Or am I missing something?

**Comment by TobyReeno** [comment]
When it comes to ignoring git files etc, I think we can hardcode it as it's obvious that these should not be copied under C2 nor zipped to release version.

**Comment by Armaldio** [comment]
About custom name, I faced two cases where i needed it (tho I can live with the current state)
1. I have a behaviour and a plugin that work together, so they are both named the same
That force me to have a structure like this : 

```
XXXX/ Plugin     /my_name/content
         /Behaviour/my_name/content
```

while I can just have `Plugin/content` and `Behaviour/content` directly

2. I have a tool that work with my plugin, so I pull all inside my structure:

```
ToolRoot/App/*
              /Plugin/plugin_name/content
```

While i can directly have:

```
ToolRoot/App/*
              /Plugin/content/
```

This is not a big issue but it can lead to deep folder structures

---

About ignore I can put assets on top folders where it does not impact things but since we could have a local configuration file, I just tough of what you could put inside to make it even more usefull

--- 

To wrap it up all,if you want to keep the tool simple, just avoid this ;)

**Comment by TobyReeno** [comment]
The directory determines the PluginID mainly. So you can just have a behavior and plugin under directory "NameB" and "NameP" for instance and after creating the workspace with `c2addona init` you can just edit the name in edittime.js. That will work and not collide with anything. It's all about the plugin's ID mainly.
